baseURL = "https://vimways.org/"
languageCode = "en-us"
title = "Vimways"
theme = "vimways"
paginate = 24
pygmentsCodeFences = true
pygmentsStyle = "friendly"
googleAnalytics = "UA-127429090-1"
pluralizeListTitles = true

[params]
  description = "The Vim advent calendar"
  images = []
  title = "Vimways"

[taxonomies]
  series = "series"
